services:
  frontend:
    build: ./frontend
    ports:
      - "8001:8000"
    environment:
      - FANOUS_SERVER_URL=http://backend:8000
      - APP_KEY=base64:2C7K9wf80G3QnJQ+EmNMuHZ3reE5hAmPr7TMoioOcw4=
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - HF_HUB_DISABLE_TELEMETRY=1
    deploy:
      resources:
        limits:
          memory: 5G
        reservations:
          memory: 4G
    restart: unless-stopped
